### PR TITLE
Discard Bugzilla issue tests where we can't reproduce failure

### PR DESCRIPTION
**Pull request by jkesselm**
Get rid of some of the junk that distracts from seeing current state of the system. See comments in each java (or lacking that, xsl) file for why I think they can go away.

 If the Bugzilla instance still existed I'd say close the issues first/also, but as far as I know it's long gone and this is the only remaining record of them.
 
 I think we can also drop 6329, since it appears to be misunderstanding about how CDATA Sections are handled. (Not that we seem to be completely consistent about that, but I believe there is no promise in XSLT that they won't be treated simply as text nodes.) But there's more room to quibble about that one.
 
 I have also, in the conformance bucket, fixed one goldfile (had the old newline-after-XML-Declaration issue), and added comments to the tests which currently fail documenting that status and explaining why their current output is in error. 
 
PLEASE NOTE: I still don't have merge authority; I'm stuck waiting for someone to accept or reject this change set.

### CODE REVIEW

**Comment by jkesselm** [comment]
...crickets? ...

I still don't have authority to fork or merge within the project, so I'm waiting for someone who does. I'm not sure I want to issue a PR for genuine issues until this cleanup has been done...

**Comment by ShaneCurcuru** [comment]
I'm not technically involved here, so can't evaluate changes, however I do want to be sure we get Joe merge permissions in github so he can keep up the good work.  Not sure why this repo doesn't just have the same perms as main Xalan ones?

**Comment by jkesselm** [comment]
> Not sure why this repo doesn't just have the same perms as main Xalan ones?

I don't seem to have merge permission on xalan-java either. Theoretically, jkesselm@apache.org should have been reauthorized for these, but something's taking its time to percolate through the process.

"Please stand by. We are making mistakes as efficiently as we can."

**Comment by garydgregory** [comment]
@jkesselm 

You are now an Apache Xalan Committer; please accept my apologies for the administrative lapse in the process.

**Comment by jkesselm** [comment]
No problem, Gary. Just trying to keep my momentum going...

--
   /_  Joe Kesselman (he/him/his)
-/ _) My Alexa skill for New Music/New Sounds fans:
   /   https://www.amazon.com/dp/B09WJ3H657/

() Plaintext Ribbon Campaign
/\ Stamp out HTML mail!
________________________________

**Pull request merged**
